Enable GitHub Pages from within action
This enables GitHub Pages from the action, so that users don’t get this error, and then have to enable it manually themselves:

```bash
Error: Get Pages site failed. Please verify that the repository has Pages enabled and configured to build using GitHub Actions, or consider exploring the `enablement` parameter for this action.
```